# Generated by Django 3.1.6 on 2021-02-08 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 8, 17, 1, 35, 223317))),
                ('visit_site', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('search_term', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, choices=[('Yelp', 'Yelp'), ('Yellow', 'Yellow')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('bookmark', models.BooleanField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('heading', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_friend', models.BooleanField(blank=True, max_length=2, null=True)),
                ('extracted_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 8, 17, 1, 35, 223317), null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap_data.message')),
                ('mutual', models.ManyToManyField(to='scrap_data.Profile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
