# Generated by Django 3.1.6 on 2021-02-16 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.URLField(blank=True, max_length=500, null=True)),
                ('date_time', models.CharField(blank=True, max_length=20, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 9, 50, 52, 325353)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extracted_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 9, 50, 52, 321651), null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap_data.facebook')),
            ],
        ),
        migrations.CreateModel(
            name='GIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap_data.facebook')),
            ],
        ),
    ]
