# Generated by Django 3.1.6 on 2021-02-19 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0002_auto_20210216_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('posted_at', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 14, 40, 44, 700327)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extracted_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 19, 14, 40, 44, 696800), null=True),
        ),
    ]
