# Generated by Django 3.1.6 on 2021-02-19 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0003_auto_20210219_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinposts',
            name='date_added_to_database',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 15, 12, 43, 152460)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extracted_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 19, 15, 12, 43, 151463), null=True),
        ),
    ]
