# Generated by Django 3.1.6 on 2021-02-22 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_data', '0005_auto_20210219_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinposts',
            name='post_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 12, 52, 37, 412859)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extracted_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 12, 52, 37, 411898), null=True),
        ),
    ]
